<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Modelo extends \AppBundle\Entity\Modelo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'nombreModelo', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'categoriaModelo', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'descripcionModelo', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'imagenModelo', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'precio', 'pedido'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'nombreModelo', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'categoriaModelo', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'descripcionModelo', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'imagenModelo', '' . "\0" . 'AppBundle\\Entity\\Modelo' . "\0" . 'precio', 'pedido'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Modelo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCategoriaModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaModelo', []);

        return parent::getCategoriaModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaModelo($categoriaModelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaModelo', [$categoriaModelo]);

        return parent::setCategoriaModelo($categoriaModelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreModelo($nombreModelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreModelo', [$nombreModelo]);

        return parent::setNombreModelo($nombreModelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreModelo', []);

        return parent::getNombreModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionModelo($descripcionModelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionModelo', [$descripcionModelo]);

        return parent::setDescripcionModelo($descripcionModelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionModelo', []);

        return parent::getDescripcionModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagenModelo($imagenModelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagenModelo', [$imagenModelo]);

        return parent::setImagenModelo($imagenModelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenModelo', []);

        return parent::getImagenModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getPedido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPedido', []);

        return parent::getPedido();
    }

    /**
     * {@inheritDoc}
     */
    public function setPedido($pedido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPedido', [$pedido]);

        return parent::setPedido($pedido);
    }

}
